services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - DB_URI=mongodb://mongo:27017/hospital-db

  mongo:
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
